#!/usr/bin/env bash
# N1 common preamble — resolves N1_ROOT, sources core libs, sets N1_HOME.
#
# Usage in skill bash snippets (generated by hooks/session-start.sh):
#   source ~/.n1-codex/preamble.sh
#
# Snippets needing specialized libs (memory, treestate, breakcheck, classify,
# related, poll, context) still source those explicitly after this line.

# Resolve from this fork, not stale Claude environment or shared host state.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/host.sh"
[ -n "${N1_ROOT:-}" ] && [ -f "$N1_ROOT/.codex-plugin/plugin.json" ] || N1_ROOT=$(n1_plugin_root)

source "$N1_ROOT/lib/config.sh"
source "$N1_ROOT/lib/step.sh"       # also loads telemetry.sh, frontmatter.sh, signals.sh
source "$N1_ROOT/lib/validation.sh"

N1_HOME=$(n1_home)
