#!/usr/bin/env python3
"""Install project-local Codex personas without changing user or Claude settings."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
MARKER = '# Generated by n1-codex; edit the source persona instead.\n'


def install(project):
    target = project.resolve() / '.codex/agents'
    pending = []
    for source in sorted((ROOT / 'agents').glob('*.md')):
        text = source.read_text()
        _, front, body = text.split('---', 2)
        fields = dict(line.split(':', 1) for line in front.splitlines() if ':' in line)
        if 'name' not in fields:
            continue
        name = 'n1-' + source.stem
        description = fields.get('description', source.stem).strip().strip('"')
        content = MARKER + f'name = {json.dumps(name)}\ndescription = {json.dumps(description)}\n'
        allowed = fields.get('tools', '')
        if allowed and not any(tool in allowed.split(', ') for tool in ('Write', 'Edit')):
            content += 'sandbox_mode = "read-only"\n'
        content += 'developer_instructions = ' + json.dumps(body.strip()) + '\n'
        path = target / (name + '.toml')
        if path.exists() and not path.read_text().startswith(MARKER):
            raise ValueError(f'Refusing to overwrite user profile: {path}')
        pending.append((path, content))
    target.mkdir(parents=True, exist_ok=True)
    for path, content in pending:
        path.write_text(content)
    print(f'Installed {len(pending)} N1 Codex personas in {target}. Start a new Codex session.')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit('Usage: install-agents.py <project-root>')
    try:
        install(Path(sys.argv[1]))
    except (OSError, ValueError) as error:
        sys.exit(str(error))
